include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.dynamo_repository.g.dart"
  
linter:
  rules:
    # Project-specific overrides can be added here if needed
