include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.dynamo_repository.g.dart"
  
linter:
  rules:
    # Allow longer lines in generated code and tests
    lines_longer_than_80_chars: false
    # Allow non-cascade style in code generation (more readable)
    cascade_invocations: false
