/// Event registry for example events.
///
/// This provides the event registry map for use with EventBusClient.
/// In a real application, this would be generated by build_runner.
library;

import 'package:dddart/dddart.dart';
import 'package:dddart_events_distributed_example/example_events.dart';

/// Event registry mapping event type names to fromJson factories.
///
/// Use this registry with EventBusClient to enable automatic
/// deserialization of distributed events.
final generatedEventRegistry =
    <String, DomainEvent Function(Map<String, dynamic>)>{
  'OrderPlacedEvent': OrderPlacedEvent.fromJson,
  'OrderPurchasedEvent': OrderPurchasedEvent.fromJson,
  'PaymentProcessedEvent': PaymentProcessedEvent.fromJson,
  'UserCreatedEvent': UserCreatedEvent.fromJson,
};
