include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "example/**"  # Examples don't need strict docs
  language:
    strict-casts: false  # Too strict for tests with dynamic JSON
    strict-inference: false  # Too pedantic for examples and tests
    strict-raw-types: false  # Too strict for tests

linter:
  rules:
    # Project-specific rule adjustments
    public_member_api_docs: false  # Internal generator code doesn't need full docs
    lines_longer_than_80_chars: false  # Allow longer lines in tests for readability
    avoid_print: false  # OK in examples
    cascade_invocations: false  # Not always more readable
    avoid_dynamic_calls: false  # Tests work with dynamic JSON
