targets:
  $default:
    builders:
      dddart_json:json_serializable:
        enabled: true
        generate_for:
          - lib/domain/*.dart
      dddart_repository_dynamodb:dynamo_repository:
        enabled: true
        generate_for:
          - lib/domain/*.dart
