// GENERATED CODE - DO NOT MODIFY BY HAND
// dart format width=80

// **************************************************************************
// EventRegistryGenerator
// **************************************************************************

// Generated event registry
// ignore_for_file: type=lint

import 'package:dddart/dddart.dart';
import 'registry_events.dart';

/// Generated event registry mapping event type names to fromJson factories.
///
/// This map is automatically generated by scanning for @Serializable
/// DomainEvent subclasses. Use this registry with EventBusClient to
/// enable automatic deserialization of distributed events.
final generatedEventRegistry =
    <String, DomainEvent Function(Map<String, dynamic>)>{
      'RegistryFixtureEvent': RegistryFixtureEvent.fromJson,
    };
