include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"

linter:
  rules:
    lines_longer_than_80_chars: false  # Allow longer lines for readability
    avoid_slow_async_io: false  # OK in examples
    cascade_invocations: false  # Not always more readable
    avoid_positional_boolean_parameters: false  # Sometimes clearer than named
    avoid_print: false  # Allow print in examples and tests
