include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "example/**"  # Examples don't need strict docs
    - "test/cognito_token_debug_test.dart"  # Debug test file
    - "test/jose_test.dart"  # Debug test file
    - "test/rsa_jwt_test.dart"  # Debug test file
    - "test/rsa_key_test.dart"  # Debug test file
    - "test/pem_verification_test.dart"  # Debug test file
    - "test/cognito_jwk_test.dart"  # Debug test file
    - "test/oauth_integration_test.dart"  # Integration test with external dependencies
  language:
    strict-casts: false  # Too strict for tests with dynamic JSON
    strict-inference: false  # Too pedantic for examples and tests
    strict-raw-types: false  # Too strict for tests

linter:
  rules:
    # Project-specific rule adjustments
    public_member_api_docs: true
    lines_longer_than_80_chars: false  # Allow longer lines in tests for readability
    avoid_dynamic_calls: false  # Sometimes necessary in tests with JSON
    cascade_invocations: false  # Not always more readable
    no_default_cases: false  # Default cases are fine for error handling
    avoid_print: false  # Allow print in examples and tests
